#!/usr/bin/env python
import sys, os
import mysync

arglen=len(sys.argv);
if arglen < 2:
	print "Usage : ",sys.argv[0], " sourceDir"
	sys.exit();


fExtList = "*.c,*.h,*.py,*.script,*.conf,*Jamfile,*cshrc*"

pList = mysync.extList(fExtList)
srcList = mysync.walktree(sys.argv[1], pList, [], len(sys.argv[1]), prn=0)
srcList.sort()

for n in srcList:
	print n[0]
	os.system("cvs status %s" %(n[0]))
